include: 
  - file: 'flatpak/flatpak_ci_initiative.yml'
    project: 'GNOME/citemplates'

variables:
  APP_ID: "org.gabmus.gfeeds"
  BUNDLE: "org.gabmus.gfeeds.flatpak"
  CONFIG_OPTS: "-Dprofile=development"
  FLATPAK_MODULE: "gfeeds"
  MANIFEST_PATH: "dist/flatpak/org.gabmus.gfeeds.json"
  RUNTIME_REPO: "https://flathub.org/repo/flathub.flatpakrepo"


flake8:
  image: python:3.10
  script:
    - pip install flake8
    - flake8 gfeeds

flatpak:
  extends: '.flatpak@x86_64'
  image: 'quay.io/gnome_infrastructure/gnome-runtime-images:x86_64-gnome-44'

flatpak@aarch64:
  extends: '.flatpak@aarch64'
  image: 'quay.io/gnome_infrastructure/gnome-runtime-images:aarch64-gnome-44'
