include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

flake8:
    image: python:3.10
    script:
        - pip install flake8
        - flake8 gfeeds

flatpak:
    variables:
        MANIFEST_PATH: "dist/flatpak/org.gabmus.gfeeds.json"
        MESON_ARGS: "-Dprofile=Devel"
        FLATPAK_MODULE: "gfeeds"
        RUNTIME_REPO: "https://flathub.org/repo/flathub.flatpakrepo"
        APP_ID: "org.gabmus.gfeeds"
        BUNDLE: "gfeeds.flatpak"
    extends: .flatpak
    rules:
        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
