[tool.poetry]
name = "gfeeds"
version = "1.0.2"
description = "News reader for GNOME"
authors = ["Gabriele Musco <gabmus@disroot.org>"]
license = "GPL3"

[tool.poetry.dependencies]
python = "^3.9"
Pillow = "^9.1.0"
python-magic = "^0.4.25"
requests = "^2.27.1"
python-dateutil = "^2.8.2"
Pygments = "^2.11.2"
pytz = "^2022.1"
readability-lxml = "^0.8.1"
humanize = "^4.0.0"
beautifulsoup4 = "^4.11.1"
lxml = "^4.8.0"
pytest = "^7.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [
  "."
]
